[macros.bash]
prefix = ["bash", "-c"]

[macros.fish]
prefix = ["fish", "-c"]

[macros.install__osx]
prefix = ["brew", "install"]

[macros.install__arch]
prefix = ["pamac", "install"]

[tasks.default]
deps = [
  "env",
  "specific",
  "fonts",
  "fish",
  "fzf-fish",
  "kitty",
  "neovim-bin",
  "vscode",
  "android",
]

[tasks.env__osx]
envs = [
  [
    "PACKAGE_NAME_BAT",
    "bat",
  ],
  [
    "PACKAGE_NAME_LIBGIT",
    "libgit2",
  ],
  [
    "PACKAGE_NAME_FD",
    "fd",
  ],
  [
    "PACKAGE_NAME_FZF",
    "fzf",
  ],
  [
    "PACKAGE_NAME_LSD",
    "lsd",
  ],
  [
    "PACKAGE_NAME_KITTY",
    "kitty",
  ],
  [
    "PACKAGE_NAME_FISH",
    "fish",
  ],
  [
    "PACKAGE_NAME_STARSHIP",
    "starship",
  ],
  [
    "PACKAGE_NAME_NEOVIM",
    "neovim",
  ],
  [
    "FONTS_DIR",
    "$HOME/Library/Fonts",
  ],
  [
    "VSCODE_DIR",
    "$HOME/Library/Application Support/Code/User"
  ],
  [
    "PACKAGE_NAME_JAVA",
    "java"
  ],
  [
    "PACKAGE_NAME_KOTLIN",
    "kotlin"
  ],
  [
    "PACKAGE_NAME_ANDROID_STUDIO",
    "android-studio"
  ],
  [
    "PACKAGE_NAME_GRADLE",
    "gradle"
  ],
]

[tasks.specific__osx]
cmds = [["echo", "skipping on osx"]]

[tasks.xclip]
cmds = [["@install", "${PACKAGE_NAME_XCLIP}"]]

[tasks.env__arch]
envs = [
  [
    "PACKAGE_NAME_BAT",
    "bat",
  ],
  [
    "PACKAGE_NAME_FD",
    "fd",
  ],
  [
    "PACKAGE_NAME_FZF",
    "fzf",
  ],
  [
    "PACKAGE_NAME_LSD",
    "lsd",
  ],
  [
    "PACKAGE_NAME_KITTY",
    "kitty",
  ],
  [
    "PACKAGE_NAME_FISH",
    "fish",
  ],
  [
    "PACKAGE_NAME_STARSHIP",
    "starship",
  ],
  [
    "PACKAGE_NAME_NEOVIM",
    "neovim",
  ],
  [
    "PACKAGE_NAME_XCLIP",
    "xclip",
  ],
  [
    "FONTS_DIR",
    "$HOME/.fonts",
  ],
  [
    "VSCODE_DIR",
    "$HOME/.config/Code/User"
  ],
]

[tasks.specific__arch]
deps = ["fish", "xclip"]
cmds = [
  [
    "@fish",
    "alias --save pbcopy 'xclip -selection clipboard'",
  ],
  [
    "@fish",
    "alias --save pbpaste 'xclip -selection clipboard -o'"
  ],
]

[tasks.fzf-deps]
cmds = [
  [
    "@install",
    "${PACKAGE_NAME_BAT}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_LIBGIT}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_FD}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_FZF}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_LSD}",
  ],
]

[tasks.kitty-bin]
rejects = [["which", "kitty"]]
cmds = [["@install", "${PACKAGE_NAME_KITTY}"]]

[tasks.fish-bin]
rejects = [["which", "fish"]]
cmds = [["@install", "${PACKAGE_NAME_FISH}"]]

[tasks.fish-change-shell]
deps = ["fish-bin"]
rejects = [["test", "$(basename ${SHELL}) = 'fish'"]]
cmds = [["@fish", "chsh -s $(which fish)"]]

[tasks.starship-bin]
rejects = [["which ", "starship"]]
cmds = [["@install", "${PACKAGE_NAME_STARSHIP}"]]

[tasks.neovim-bin]
rejects = [["which ", "nvim"]]
cmds = [["@install", "${PACKAGE_NAME_NEOVIM}"]]

[tasks.starship]
deps = ["starship-bin"]
links = [[".config/starship.toml", "config/starship/starship.toml"]]

[tasks.fzf-fish]
deps = ["fzf-deps"]

[tasks.fish]
deps = ["fish-bin", "fish-change-shell", "starship"]
links = [
  [
    ".config/fish/config.fish",
    "config/fish/config.fish",
  ],
  [
    ".config/fish/conf.d",
    "config/fish/conf.d",
  ],
  [
    ".config/fish/functions",
    "config/fish/functions",
  ],
]

[tasks.kitty]
deps = ["kitty-bin"]
links = [[".config/kitty/kitty.conf", "config/kitty/kitty.conf"]]

[tasks.vscode]
accepts = [["which", "code"]]
envs = [
  [ "NODE_OPTIONS", "--throw-deprecation" ]
]
cmds = [
  [
    "@fish",
    "cat $HM_SRC/config/vscode/extensions.txt | xargs -n1 -I{} -- code --install-extension {} --force",
  ],
]
links = [
  [
    "${VSCODE_DIR}/settings.json",
    "config/vscode/settings.json",
  ],
  [
    "${VSCODE_DIR}/keybindings.json",
    "config/vscode/keybindings.json",
  ],
]

[tasks.fonts]
cmds = [
  [
    "@fish",
    "mkdir -p ${FONTS_DIR} && cp -a $HM_SRC/config/fonts ${FONTS_DIR}",
  ],
]

[tasks.android]
cmds = [
  [
    "@install",
    "${PACKAGE_NAME_JAVA}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_KOTLIN}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_GRADLE}",
  ],
  [
    "@install",
    "${PACKAGE_NAME_ANDROID_STUDIO}",
  ],
]
links = [[".ideavimrc", "config/androidstudio/.ideavimrc"]]